import type { ToolId } from "./types";

export const TOOL_LABELS: Record<ToolId, string> = {
  pan: "Перемещение холста",
  selection: "Выбор",
  rectangle: "Прямоугольник",
  ellipse: "Эллипс",
  diamond: "Ромб",
  triangle: "Треугольник",
  hexagon: "Шестиугольник",
  star: "Звезда",
  cloud: "Облако",
  line: "Линия",
  arrow: "Стрелка",
  measure: "Линейка",
  sticky: "Стикер",
  callout: "Комментарий",
  table: "Таблица",
  frame: "Фрейм",
  embed: "Встроенная страница",
  advanced: "Premium-фигура",
  code: "Блок кода",
  text: "Текст",
  freedraw: "Карандаш",
  highlighter: "Маркер",
  sticker: "Иконки и стикеры",
  eyedropper: "Пипетка стиля",
  eraser: "Ластик",
  laser: "Лазерная указка",
  lasso: "Выделение лассо",
  image: "Изображение",
};
